development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: redis
  url: redis://localhost:6379

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: web_socket_rails_production
